### ISSUE TITLE
different errors for pyarrow-0.2.post and  pyarrow-0.3.pre on ec2

### ISSUE THREAD

**Issue by data-steve** [conda-forge/pyarrow-feedstock#23]
Conda Environment on EC2

```
[steven.simpson@ip-10-20-74-154 ~]$ /mnt/var/lib/anaconda2/bin/conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /mnt/var/lib/anaconda2  (read only)
    default environment : /mnt/var/lib/anaconda2
       envs directories : /home/steven.simpson/.conda/envs
                          /mnt/var/lib/anaconda2/envs
          package cache : /home/steven.simpson/.conda/envs/.pkgs
                          /mnt/var/lib/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False


[steven.simpson@ip-10-20-74-154 ~]$ /mnt/var/lib/anaconda2/bin/conda list
# packages in environment at /mnt/var/lib/anaconda2:
#
_nb_ext_conf              0.2.0                    py27_0  
alabaster                 0.7.8                    py27_0  
anaconda                  4.1.1               np111py27_0  
anaconda-client           1.4.0                    py27_0  
anaconda-navigator        1.2.1                    py27_0  
argcomplete               1.0.0                    py27_1  
astropy                   1.2.1               np111py27_0  
babel                     2.3.3                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.4                      py27_0  
beautifulsoup4            4.4.1                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
bokeh                     0.12.0                   py27_0  
boto                      2.40.0                   py27_0  
bottleneck                1.1.0               np111py27_0  
cairo                     1.12.18                       6  
cdecimal                  2.3                      py27_2  
cffi                      1.6.0                    py27_0  
chest                     0.2.3                    py27_0  
click                     6.6                      py27_0  
cloudpickle               0.2.1                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.1.6                    py27_0  
conda-build               1.21.3                   py27_0  
conda-env                 2.5.1                    py27_0  
configobj                 5.0.6                    py27_0  
configparser              3.5.0b2                  py27_1  
contextlib2               0.5.3                    py27_0  
cryptography              1.4                      py27_0  
curl                      7.49.0                        0  
cycler                    0.10.0                   py27_0  
cython                    0.24                     py27_0  
cytoolz                   0.8.0                    py27_0  
dask                      0.10.0                   py27_0  
datashape                 0.5.2                    py27_0  
decorator                 4.0.10                   py27_0  
dill                      0.2.5                    py27_0  
docutils                  0.12                     py27_2  
dynd-python               0.7.2                    py27_0  
entrypoints               0.2.2                    py27_0  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
fastcache                 1.0.2                    py27_1  
flask                     0.11.1                   py27_0  
flask-cors                2.1.2                    py27_0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.0.5                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.1.1                    py27_0  
greenlet                  0.4.10                   py27_0  
grin                      1.2.1                    py27_3  
h5py                      2.6.0               np111py27_1  
hdf5                      1.8.16                        0  
heapdict                  1.0.0                    py27_1  
idna                      2.1                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.16                   py27_0  
ipykernel                 4.3.1                    py27_0  
ipython                   4.2.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.1.1                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.2                      py27_1  
jedi                      0.9.0                    py27_1  
jinja2                    2.8                      py27_1  
jpeg                      8d                            1  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            4.3.0                    py27_0  
jupyter_console           4.1.1                    py27_0  
jupyter_core              4.1.0                    py27_0  
libdynd                   0.7.2                         0  
libffi                    3.2.1                         0  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         2  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.11.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.6.0                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                1.5.1               np111py27_0  
mistune                   0.7.2                    py27_0  
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py27_2  
mpmath                    0.19                     py27_1  
multipledispatch          0.4.8                    py27_0  
nb_anacondacloud          1.1.0                    py27_0  
nb_conda                  1.1.0                    py27_0  
nb_conda_kernels          1.0.3                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.0.1                    py27_0  
nbpresent                 3.0.2                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.1                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  4.2.1                    py27_0  
numba                     0.26.0              np111py27_0  
numexpr                   2.6.0               np111py27_0  
numpy                     1.11.1                   py27_0  
odo                       0.5.0                    py27_1  
openpyxl                  2.3.2                    py27_0  
openssl                   1.0.2h                        1  
pandas                    0.18.1              np111py27_0  
partd                     0.3.4                    py27_0  
patchelf                  0.9                           0  
path.py                   8.2.1                    py27_0  
pathlib2                  2.1.0                    py27_0  
patsy                     0.4.1                    py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.0.1                    py27_0  
pickleshare               0.7.2                    py27_0  
pillow                    3.2.0                    py27_1  
pip                       8.1.2                    py27_0  
pixman                    0.32.6                        0  
ply                       3.8                      py27_0  
psutil                    4.3.0                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.31                   py27_0  
pyasn1                    0.1.9                    py27_0  
pycairo                   1.10.0                   py27_0  
pycosat                   0.6.1                    py27_1  
pycparser                 2.14                     py27_1  
pycrypto                  2.6.1                    py27_4  
pycurl                    7.43.0                   py27_0  
pyflakes                  1.2.3                    py27_0  
pygments                  2.1.3                    py27_0  
pyopenssl                 0.16.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      4.11.4                   py27_3  
pytables                  3.2.2               np111py27_4  
pytest                    2.9.2                    py27_0  
python                    2.7.12                        1  
python-dateutil           2.5.3                    py27_0  
pytz                      2016.4                   py27_0  
pyyaml                    3.11                     py27_4  
pyzmq                     15.2.0                   py27_1  
qt                        4.8.7                         3  
qtconsole                 4.2.1                    py27_0  
qtpy                      1.0.2                    py27_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py27_0  
requests                  2.10.0                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.7                   py27_0  
scikit-image              0.12.3              np111py27_1  
scikit-learn              0.17.1              np111py27_2  
scipy                     0.17.1              np111py27_1  
setuptools                23.0.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.16.9                   py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.3                    py27_0  
sphinx                    1.4.1                    py27_0  
sphinx_rtd_theme          0.1.9                    py27_0  
spyder                    2.3.9                    py27_0  
sqlalchemy                1.0.13                   py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.6.1               np111py27_1  
sympy                     1.0                      py27_0  
terminado                 0.6                      py27_0  
tk                        8.5.18                        0  
toolz                     0.8.0                    py27_0  
tornado                   4.3                      py27_1  
traitlets                 4.2.1                    py27_0  
unicodecsv                0.14.1                   py27_0  
werkzeug                  0.11.10                  py27_0  
wheel                     0.29.0                   py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.2                    py27_0  
xlwt                      1.1.2                    py27_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.4                         0  
zlib                      1.2.8                         3  

```

I install pyarrow ver 0.2.post because that's what I was able to get working on my machine.

```
[steven.simpson@ip-10-20-74-154 ~]$ sudo su
[root@ip-10-20-74-154 steven.simpson]# /mnt/var/lib/anaconda2/bin/conda install -c conda-forge pyarrow=0.2.post
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /mnt/var/lib/anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0         1017 B  conda-forge
    jemalloc-4.4.0             |                0         2.3 MB  conda-forge
    parquet-cpp-1.1.0pre       |                1         1.6 MB  conda-forge
    ruamel_yaml-0.11.14        |           py27_0         420 KB  conda-forge
    arrow-cpp-0.3.pre          |      np111py27_1         1.3 MB  conda-forge
    conda-4.2.13               |           py27_0         374 KB  conda-forge
    pyarrow-0.2.post           |      np111py27_0         3.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         9.2 MB

The following NEW packages will be INSTALLED:

    arrow-cpp:   0.3.pre-np111py27_1  conda-forge
    jemalloc:    4.4.0-0              conda-forge
    parquet-cpp: 1.1.0pre-1           conda-forge
    pyarrow:     0.2.post-np111py27_0 conda-forge

The following packages will be UPDATED:

    conda:       4.1.6-py27_0                     --> 4.2.13-py27_0  conda-forge
    conda-env:   2.5.1-py27_0                     --> 2.6.0-0        conda-forge
    ruamel_yaml: 0.11.7-py27_0                    --> 0.11.14-py27_0 conda-forge

Proceed ([y]/n)? y  

Fetching packages ...
conda-env-2.6. 100% |######################################################################| Time: 0:00:00   1.40 MB/s
jemalloc-4.4.0 100% |######################################################################| Time: 0:00:01   2.25 MB/s
parquet-cpp-1. 100% |######################################################################| Time: 0:00:00   1.97 MB/s
ruamel_yaml-0. 100% |######################################################################| Time: 0:00:00 911.23 kB/s
arrow-cpp-0.3. 100% |######################################################################| Time: 0:00:00   1.63 MB/s
conda-4.2.13-p 100% |######################################################################| Time: 0:00:00 659.74 kB/s
pyarrow-0.2.po 100% |######################################################################| Time: 0:00:00   3.72 MB/s
Extracting packages ...
[      COMPLETE      ]|#########################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#########################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#########################################################################################| 100%
```

When I try to `import pyarrow` I get a `libarrow_io.so` error

```
[steven.simpson@ip-10-20-74-154 ~]$ python
Python 2.7.12 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/pyarrow/__init__.py", line 28, in <module>
    import pyarrow.config
ImportError: libarrow_io.so: cannot open shared object file: No such file or directory
>>> quit()
```

So I try to update pyarrow to `0.3.pre`, [which I've had trouble with before](https://github.com/conda-forge/pyarrow-feedstock/issues/20#issuecomment-289266763) 

```
[steven.simpson@ip-10-20-74-154 ~]$ sudo su
[root@ip-10-20-74-154 steven.simpson]# /mnt/var/lib/anaconda2/bin/conda install -c conda-forge pyarrow
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /mnt/var/lib/anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyarrow-0.3.pre            |      np111py27_0         2.3 MB  conda-forge

The following packages will be UPDATED:

    pyarrow: 0.2.post-np111py27_0 conda-forge --> 0.3.pre-np111py27_0 conda-forge

Proceed ([y]/n)? yes

Fetching packages ...
pyarrow-0.3.pr 100% |######################################################################| Time: 0:00:01   2.25 MB/s
Extracting packages ...
[      COMPLETE      ]|#########################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#########################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#########################################################################################| 100%
[root@ip-10-20-74-154 steven.simpson]# exit
```

Then try to rerun `import pyarrow` in python interpreter and get a Numpy related error

```
[steven.simpson@ip-10-20-74-154 ~]$ python
Python 2.7.12 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/pyarrow/__init__.py", line 28, in <module>
    import pyarrow._config
ImportError: /mnt/var/lib/anaconda2/lib/python2.7/site-packages/pyarrow/_config.so: undefined symbol: _ZN5arrow2py9InitNumPyEv
```

What's weird and frustrating is that I can get pyarrow working on my local conda env:

```
alabaster                 0.7.9                    py27_0  
anaconda                  custom                   py27_0  
anaconda-client           1.6.0                    py27_0  
anaconda-navigator        1.5.0                    py27_0  
anaconda-project          0.4.1                    py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               1.0.0                    py27_1  
arrow-cpp                 0.2.post                      0    conda-forge
astroid                   1.4.9                    py27_0  
astropy                   1.3                 np111py27_0  
babel                     2.3.4                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0  
beautifulsoup4            4.5.3                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
bokeh                     0.12.5                   py27_0    conda-forge
boto                      2.45.0                   py27_0  
boto3                     1.4.4                    py27_0    conda-forge
botocore                  1.5.39                   py27_0    conda-forge
bottleneck                1.2.0               np111py27_0  
cdecimal                  2.3                      py27_2  
cffi                      1.9.1                    py27_0  
chardet                   2.3.0                    py27_0  
chest                     0.2.3                    py27_0  
click                     6.7                      py27_0  
cloudpickle               0.2.2                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.3.16                   py27_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py27_0  
configparser              3.5.0                    py27_0  
contextlib2               0.5.4                    py27_0  
cryptography              1.7.1                    py27_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py27_0  
cython                    0.25.2                   py27_0  
cytoolz                   0.8.2                    py27_0  
dask                      0.14.1                   py27_0    conda-forge
datashape                 0.5.4                    py27_0  
decorator                 4.0.11                   py27_0  
dill                      0.2.5                    py27_0  
distributed               1.16.1                   py27_0    conda-forge
docutils                  0.13.1                   py27_0  
entrypoints               0.2.2                    py27_0  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
fastcache                 1.0.2                    py27_1  
feather-format            0.3.1                    py27_1    conda-forge
flask                     0.12                     py27_0  
flask-cors                3.0.2                    py27_0  
freetype                  2.7                           1    conda-forge
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.0.5                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.2.1                    py27_0  
graphviz                  2.38.0                        4    conda-forge
greenlet                  0.4.11                   py27_0  
grin                      1.2.1                    py27_3  
h5py                      2.6.0               np111py27_2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py27_1  
icu                       54.1                          0  
idna                      2.2                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.18                   py27_0  
ipykernel                 4.5.2                    py27_0  
ipython                   5.1.0                    py27_1  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                5.2.2                    py27_1  
isort                     4.2.5                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.3                      py27_0  
jedi                      0.9.0                    py27_1  
jemalloc                  4.4.0                         0    conda-forge
jinja2                    2.9.4                    py27_0  
jmespath                  0.9.2                    py27_0    conda-forge
jpeg                      9b                            0  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_0    conda-forge
jupyter_client            4.4.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_core              4.2.1                    py27_0  
lazy-object-proxy         1.2.2                    py27_0  
libiconv                  1.14                          0  
libpng                    1.6.28                        0    conda-forge
libtiff                   4.0.6                         3  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.15.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.7.2                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                2.0.0               np111py27_3    conda-forge
mistune                   0.7.3                    py27_1  
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py27_3  
mpmath                    0.19                     py27_1  
msgpack-python            0.4.8                    py27_0    conda-forge
multipledispatch          0.4.9                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.2.0                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.2                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  4.3.1                    py27_0  
numba                     0.30.1              np111py27_0  
numexpr                   2.6.1               np111py27_1  
numpy                     1.11.2                   py27_0  
numpydoc                  0.6.0                    py27_0  
odo                       0.5.0                    py27_1  
olefile                   0.44                     py27_0    conda-forge
openpyxl                  2.4.1                    py27_0  
openssl                   1.0.2k                        1  
pandas                    0.19.2              np111py27_1  
pandas-datareader         0.3.0.post0               <pip>
parquet-cpp               0.1.pre                      14    conda-forge
partd                     0.3.7                    py27_0  
path.py                   10.0                     py27_0  
pathlib2                  2.2.0                    py27_0  
patsy                     0.4.1                    py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pillow                    4.1.0                    py27_0    conda-forge
pip                       9.0.1                    py27_1  
ply                       3.9                      py27_0  
prompt_toolkit            1.0.9                    py27_0  
psutil                    5.0.1                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.32                   py27_0  
pyarrow                   0.2.post            np111py27_0    conda-forge
pyasn1                    0.1.9                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_1  
pycparser                 2.17                     py27_0  
pycrypto                  2.6.1                    py27_4  
pycurl                    7.43.0                   py27_2  
pyflakes                  1.5.0                    py27_0  
pygments                  2.1.3                    py27_0  
pylint                    1.6.4                    py27_1  
pyopenssl                 16.2.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_1  
pytables                  3.3.0               np111py27_0  
pytest                    3.0.5                    py27_0  
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
python-graphviz           0.6                      py27_1    conda-forge
python.app                1.2                      py27_4  
pytz                      2016.10                  py27_0  
pyyaml                    3.12                     py27_0  
pyzmq                     16.0.2                   py27_0  
qt                        5.6.2                         0  
qtawesome                 0.4.3                    py27_0  
qtconsole                 4.2.1                    py27_1  
qtpy                      1.2.1                    py27_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py27_0  
requests                  2.12.4                   py27_0  
requests-file             1.4.1                     <pip>
requests-ftp              0.3.1                     <pip>
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_1  
s3fs                      0.0.9                    py27_0    conda-forge
s3transfer                0.1.10                   py27_1    conda-forge
scandir                   1.4                      py27_0  
scikit-image              0.12.3              np111py27_1  
scikit-learn              0.17.1              np111py27_2  
scikit-learn              0.17                      <pip>
scipy                     0.18.1              np111py27_0  
seaborn                   0.7.1                    py27_0  
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.3                    py27_0  
sortedcontainers          1.5.3                    py27_0    conda-forge
sphinx                    1.5.1                    py27_0  
spyder                    3.1.2                    py27_0  
sqlalchemy                1.1.5                    py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.6.1               np111py27_1  
subprocess32              3.2.7                    py27_0  
sympy                     1.0                      py27_0  
tblib                     1.3.2                    py27_0    conda-forge
terminado                 0.6                      py27_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py27_0  
tornado                   4.4.2                    py27_0  
traitlets                 4.3.1                    py27_0  
unicodecsv                0.14.1                   py27_0  
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.11.15                  py27_0  
wheel                     0.29.0                   py27_0  
widgetsnbextension        1.2.6                    py27_0  
wrapt                     1.10.8                   py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.6                    py27_0  
xlwings                   0.10.2                   py27_0  
xlwt                      1.2.0                    py27_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zict                      0.1.1                    py27_0    conda-forge
zlib                      1.2.8                         3  




               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/steve/anaconda  (writable)
    default environment : /Users/steve/anaconda
       envs directories : /Users/steve/anaconda/envs
          package cache : /Users/steve/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

```

**Comment by wesm** [comment]
Builds will take a little while to filter through to anaconda.org, I will verify that things are working in a couple hours
