### ISSUE TITLE
ImportError: undefined symbol

### ISSUE THREAD

**Issue by gwerbin** [conda-forge/pyarrow-feedstock#58]
Issue: `ImportError: undefined symbol` 

Not sure if it's an Arrow issue or a Conda one. Or (more likely) just something broken in my environment.

I had pyarrow 0.11 installed at first. Downgrading to 0.10 and 0.9 didn't fix the problem.

```python
import pyarrow.parquet as pq
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/<redacted>/projects/<redacted>/conda-env/lib/python3.6/site-packages/pyarrow/__init__.py", line 47, in <module>
#     from pyarrow.lib import cpu_count, set_cpu_count
# ImportError: /<redacted>/projects/<redacted>/conda-env/lib/python3.6/site-packages/pyarrow/../../../libarrow.so.0: undefined symbol: _ZN5boost13match_resultsIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS5_EEEE12maybe_assignERKS9_
```

<br>
Environment (<code>conda list</code>):
<details>

```
# packages in environment at /opt/app/data/home_extenstion/gregory-werbin/projects/tts-classification/conda-env:
#
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0  
appdirs                   1.4.3                     <pip>
arrow-cpp                 0.9.0            py36h70250a7_7    conda-forge
asn1crypto                0.24.0                   py36_0  
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
backcall                  0.1.0                    py36_0  
bidict                    0.17.3                     py_0    conda-forge
blas                      1.0                         mkl  
boost-cpp                 1.67.0               h14c3975_4  
boto                      2.49.0                   py36_0  
boto3                     1.9.21                   py36_0  
botocore                  1.12.23                  py36_0  
bz2file                   0.98                      <pip>
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
category_encoders         1.3.0                      py_0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
cffi                      1.11.5           py36he75722e_1  
chardet                   3.0.4                    py36_1  
ConfigArgParse            0.13.0                    <pip>
cryptography              2.3.1            py36hc365091_0  
cycler                    0.10.0                   py36_0  
cymem                     2.0.2            py36hfd86e86_0  
cytoolz                   0.9.0.1          py36h14c3975_1  
datrie                    0.7.1                     <pip>
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py36_0  
dill                      0.2.8.2                  py36_0  
docutils                  0.14                     py36_0  
expat                     2.2.6                he6710b0_0  
fastparquet               0.1.6                    py36_0    conda-forge
fasttext                  0.1.0                hfc679d8_0    conda-forge
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
gensim                    3.6.0                     <pip>
gitdb2                    2.0.5                     <pip>
GitPython                 2.1.11                    <pip>
glib                      2.56.2               hd408876_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
icu                       58.2                 h9c2bf20_1  
idna                      2.7                      py36_0  
imbalanced-learn          0.4.1                      py_0    conda-forge
intel-openmp              2019.0                      118  
ipykernel                 5.1.0            py36h39e3cac_0  
ipython                   7.0.1            py36h39e3cac_0  
ipython_genutils          0.2.0                    py36_0  
jedi                      0.13.1                   py36_0  
jmespath                  0.9.3                    py36_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0                     <pip>
jupyter_client            5.2.3                    py36_0  
jupyter_core              4.4.0                    py36_0  
kiwisolver                1.0.1            py36hf484d3e_0  
libboost                  1.67.0               h46d08c1_4  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.35               hbc83047_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxgboost                0.80                 hfc679d8_1    conda-forge
libxml2                   2.9.8                h26e45fe_1  
lightgbm                  2.2.1            py36hfc679d8_0    conda-forge
llvmlite                  0.25.0           py36hd28b015_1    conda-forge
matplotlib                3.0.0            py36h5429711_0  
mkl                       2019.0                      118  
mkl_fft                   1.0.6            py36h7dd41cf_0  
mkl_random                1.0.1            py36h4414c95_1  
more-itertools            4.3.0                 py36_1000    conda-forge
msgpack-numpy             0.4.3.2                  py36_0  
msgpack-python            0.5.6            py36h6bb024c_1  
murmurhash                1.0.1            py36he6710b0_0  
ncurses                   6.1                  hf484d3e_0  
nltk                      3.3.0                    py36_0  
numba                     0.40.0           py36hf8a1672_0    conda-forge
numpy                     1.15.2           py36h1d66e8a_1  
numpy-base                1.15.2           py36h81de0dd_1  
openssl                   1.0.2p               h470a237_1    conda-forge
pandas                    0.23.4           py36h04863e7_0  
parquet-cpp               1.4.0                h83d4a3d_2    conda-forge
parso                     0.3.1                    py36_0  
patsy                     0.5.0                    py36_0  
pcre                      8.42                 h439df22_0  
pexpect                   4.6.0                    py36_0  
pickleshare               0.7.5                    py36_0  
pip                       10.0.1                   py36_0  
plac                      0.9.6                    py36_0  
pluggy                    0.8.0                      py_0    conda-forge
preshed                   2.0.1            py36he6710b0_0  
prompt_toolkit            2.0.6                    py36_0  
ptyprocess                0.6.0                    py36_0  
py                        1.7.0                      py_0    conda-forge
py-xgboost                0.80             py36hfc679d8_1    conda-forge
pyarrow                   0.9.0            py36hfc679d8_2    conda-forge
pycparser                 2.19                     py36_0  
pygments                  2.2.0                    py36_0  
pyopenssl                 18.0.0                   py36_0  
pyparsing                 2.2.2                    py36_0  
pyqt                      5.9.2            py36h05f1152_2  
pysocks                   1.6.8                    py36_0  
pytest                    3.9.1                 py36_1000    conda-forge
python                    3.6.6                h6e4f718_2  
python-dateutil           2.7.3                    py36_0  
pytz                      2018.5                   py36_0  
PyYAML                    3.13                      <pip>
pyzmq                     17.1.2           py36h14c3975_0  
qt                        5.9.6                h8703b6f_2  
ratelimiter               1.2.0.post0               <pip>
readline                  7.0                  h7b6447c_5  
regex                     2018.08.29       py36h7b6447c_0  
requests                  2.19.1                   py36_0  
s3transfer                0.1.13                   py36_0  
scikit-learn              0.20.0           py36h4989274_1  
scipy                     1.1.0            py36hfa4b5c9_1  
setuptools                40.4.3                   py36_0  
simplegeneric             0.8.1                    py36_2  
sip                       4.19.8           py36hf484d3e_0  
six                       1.11.0                   py36_1  
smart_open                1.7.1                    py36_0  
smmap2                    2.0.5                     <pip>
snakemake                 5.3.0                     <pip>
spacy                     2.0.16           py36h962f231_0  
sqlite                    3.25.2               h7b6447c_0  
statsmodels               0.9.0            py36h035aef0_0  
thinc                     6.12.0           py36h4989274_0  
thrift                    0.11.0           py36hfc679d8_1    conda-forge
tk                        8.6.8                hbc83047_0  
toolz                     0.9.0                    py36_0  
tornado                   5.1.1            py36h7b6447c_0  
tqdm                      4.27.0             pyha03479a_0    <redacted>
traitlets                 4.3.2                    py36_0  
ujson                     1.35             py36h14c3975_0  
urllib3                   1.23                     py36_0  
wcwidth                   0.1.7                    py36_0  
wheel                     0.32.1                   py36_0  
wrapt                     1.10.11          py36h14c3975_2  
xlrd                      1.1.0                    py36_1  
xz                        5.2.4                h14c3975_4  
zeromq                    4.2.5                hf484d3e_1  
zlib                      1.2.11               ha838bed_2  
```
</details>
<br>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```

     active environment : /<redacted>/projects/<redacted>/conda-env
    active env location : /<redacted>/projects/<redacted>/conda-env
            shell level : 1
       user config file : /<redacted>/.condarc
 populated config files : /<redacted>/.condarc
          conda version : 4.5.0
    conda-build version : 3.0.31
         python version : 3.6.1.final.0
       base environment : /<redacted>/anaconda3  (read only)
           channel URLs : <redacted>/linux-64
                          <redacted>/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/app/anaconda3/pkgs
                          /<redacted>/.conda/pkgs
       envs directories : /<redacted>/.conda/envs
                          /<redacted>/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.1 Linux/3.10.0-514.26.2.el7.x86_64 rhel/7.3 glibc/2.17
                UID:GID : 51757:51714
             netrc file : None
           offline mode : False
```
</details>

**Comment by wesm** [comment]
Try uninstalling `libboost`

**Comment by spk83** [comment]
Getting similar error and uninstalling `libboost` fixed it. but this may be the root cause here?  https://github.com/ContinuumIO/anaconda-issues/issues/9287

**Comment by xhochy** [comment]
Uninstalling `libboost` is the correct option here. Don't mix packages from `defaults` and `conda-forge`.
