### ISSUE TITLE
Installing with py2.7 causing errors

### ISSUE THREAD

**Issue by savingoyal** [conda-forge/pyarrow-feedstock#78]
Issue:

Unable to install `pyarrow==0.13.0` with `py27`.
The following command fails for me - 
```
/root/miniconda3/bin/conda create --name py27_env python==2.7.5 pyarrow==0.13.0 -c conda-forge
```

```
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - pyarrow==0.13.0 -> arrow-cpp[version='>=0.13.0,<0.14.0a0,>=0.13.0,<1.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - pyarrow==0.13.0 -> arrow-cpp[version='>=0.13.0,<0.14.0a0,>=0.13.0,<1.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> tk[version='>=8.6.9,<8.7.0a0']
  - python==2.7.5
Use "conda search <package> --info" to see the dependencies for each package.
```
If I roll back `pyarrow` to `v0.11.1`, I am able to create the environment - 
```
/root/miniconda3/bin/conda create --name py27_env python==2.7.5 pyarrow==0.11.1 -c conda-forge
```
but I run into this issue - 
```
Python 2.7.5 |Continuum Analytics, Inc.| (default, Nov  4 2013, 15:30:26)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/py27_env/lib/python2.7/site-packages/pyarrow/__init__.py", line 54, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /root/miniconda3/envs/py27_env/lib/python2.7/site-packages/pyarrow/lib.so: undefined symbol: _ZNK5arrow11RecordBatch11column_nameB5cxx11Ei
```
<details>

```
## Package Plan ##

  environment location: /root/miniconda3/envs/py27_env

  added / updated specs:
    - pyarrow==0.11.1
    - python==2.7.5


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    arrow-cpp-0.11.1           |   py27h3bd774a_1         6.1 MB  conda-forge
    certifi-2019.3.9           |           py27_0         149 KB  conda-forge
    futures-3.2.0              |        py27_1000          24 KB  conda-forge
    numpy-1.16.4               |   py27h95a1406_0         4.2 MB  conda-forge
    openssl-1.0.1k             |                1         2.6 MB
    pandas-0.24.2              |   py27hb3f55d8_0        10.9 MB  conda-forge
    parquet-cpp-1.5.1          |                3           3 KB  conda-forge
    pip-19.1                   |           py27_0         1.8 MB  conda-forge
    pyarrow-0.11.1             |py27hbbcf98d_1002         1.9 MB  conda-forge
    python-2.7.5               |                3        12.3 MB
    setuptools-41.0.1          |           py27_0         650 KB  conda-forge
    six-1.12.0                 |        py27_1000          21 KB  conda-forge
    sqlite-3.19.3              |                1         1.3 MB  conda-forge
    system-5.8                 |                2         170 KB
    thrift-cpp-0.11.0          |                2         2.6 MB  conda-forge
    wheel-0.33.4               |           py27_0          34 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        44.9 MB

The following NEW packages will be INSTALLED:

  arrow-cpp          conda-forge/linux-64::arrow-cpp-0.11.1-py27h3bd774a_1
  boost-cpp          conda-forge/linux-64::boost-cpp-1.68.0-h11c811c_1000
  bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
  certifi            conda-forge/linux-64::certifi-2019.3.9-py27_0
  futures            conda-forge/linux-64::futures-3.2.0-py27_1000
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  libblas            conda-forge/linux-64::libblas-3.8.0-7_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-7_openblas
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-8.2.0-hdf63c60_1
  libgfortran        conda-forge/linux-64::libgfortran-3.0.0-1
  liblapack          conda-forge/linux-64::liblapack-3.8.0-7_openblas
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-8.2.0-hdf63c60_1
  ncurses            conda-forge/linux-64::ncurses-5.9-10
  numpy              conda-forge/linux-64::numpy-1.16.4-py27h95a1406_0
  openblas           conda-forge/linux-64::openblas-0.3.5-ha44fe06_0
  openssl            pkgs/free/linux-64::openssl-1.0.1k-1
  pandas             conda-forge/linux-64::pandas-0.24.2-py27hb3f55d8_0
  parquet-cpp        conda-forge/noarch::parquet-cpp-1.5.1-3
  pip                conda-forge/linux-64::pip-19.1-py27_0
  pyarrow            conda-forge/linux-64::pyarrow-0.11.1-py27hbbcf98d_1002
  python             pkgs/free/linux-64::python-2.7.5-3
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  pytz               conda-forge/noarch::pytz-2019.1-py_0
  readline           conda-forge/linux-64::readline-6.2-0
  setuptools         conda-forge/linux-64::setuptools-41.0.1-py27_0
  six                conda-forge/linux-64::six-1.12.0-py27_1000
  sqlite             conda-forge/linux-64::sqlite-3.19.3-1
  system             pkgs/free/linux-64::system-5.8-2
  thrift-cpp         conda-forge/linux-64::thrift-cpp-0.11.0-2
  tk                 conda-forge/linux-64::tk-8.5.19-2
  wheel              conda-forge/linux-64::wheel-0.33.4-py27_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h14c3975_1004
```
</details>
Any pointers around what might be going wrong?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /root/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0
ca-certificates           2019.1.23                     0
certifi                   2019.3.9                 py37_0
cffi                      1.12.2           py37h2e261b9_1
chardet                   3.0.4                    py37_1
conda                     4.6.14                   py37_0
cryptography              2.6.1            py37h1ba5d50_0
idna                      2.8                      py37_0
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libstdcxx-ng              8.2.0                hdf63c60_1
ncurses                   6.1                  he6710b0_1
openssl                   1.1.1b               h7b6447c_1
pip                       19.0.3                   py37_0
pycosat                   0.6.3            py37h14c3975_0
pycparser                 2.19                     py37_0
pyopenssl                 19.0.0                   py37_0
pysocks                   1.6.8                    py37_0
python                    3.7.3                h0371630_0
readline                  7.0                  h7b6447c_5
requests                  2.21.0                   py37_0
ruamel_yaml               0.15.46          py37h14c3975_0
setuptools                41.0.0                   py37_0
six                       1.12.0                   py37_0
sqlite                    3.27.2               h7b6447c_0
tk                        8.6.8                hbc83047_0
urllib3                   1.24.1                   py37_0
wheel                     0.33.1                   py37_0
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zlib                      1.2.11               h7b6447c_3
```

</details>
<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /root/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-45-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```
</details>

**Comment by savingoyal** [comment]
Also, I don't run into any of these issues when using `py3.6`

**Comment by xhochy** [comment]
This is because you pin to an old version of Python which as `conda` correctly pointed out relies on an old OpenSSL version.

Please use a more recent Python 2.7 version to combine the latest release of `pyarrow` and `python=2.7`.
